#%Vocabulary 1.0
base: http://a.ml/vocabularies/security#
usage: Vocabulary for HTTP security information
uses:
  core: core.yaml
  data: data_model.yaml
classTerms:
  ApiKeySettings:
    displayName: API Key Settings
    description: Settings for an API Key security scheme
    extends: Settings
  HttpSettings:
    displayName: HTTP Settings
    description: Settings for an HTTP security scheme
    extends: Settings
  OAuth1Settings:
    displayName: OAuth1 Settings
    description: Settings for an OAuth1 security scheme
    extends: Settings
  OAuth2Settings:
    displayName: OAuth2 Settings
    description: Settings for an OAuth2 security scheme
    extends: Settings
  OpenIdConnectSettings:
    displayName: OpenID Settings
    description: Settings for an OpenID security scheme
    extends: Settings
  ParametrizedSecurityScheme:
    displayName: Parametrized Security Scheme
  Scope:
    displayName: Scope
  SecurityScheme:
    displayName: Security Scheme
    description: Authentication and access control mechanism defined in an API
  Settings:
    displayName: Settings
    description: Settings for a security scheme
propertyTerms:
  accessTokenUri:
    displayName: access token URI
    range: string
  additionalProperties:
    displayName: additional properties
    range: data.Node
  authorizationGrant:
    displayName: authorization grant
    range: string
  authorizationUri:
    displayName: authorization URI
    range: string
  bearerFormat:
    displayName: bearer format
    range: string
  description:
    displayName: description
    description: Human readable description for the scope
    extends: core.description
    range: string
  flow:
    displayName: flow
    range: string
  in:
    displayName: in
    range: string
  name:
    displayName: name
    range: string
  openIdConnectUrl:
    displayName: OpenID connect URL
    range: string
  refreshUri:
    displayName: refresh URI
    range: string
  requestTokenUri:
    displayName: request token URI
    range: string
  scheme:
    displayName: scheme
    range: SecurityScheme
  scope:
    displayName: scope
    range: Scope
  security:
    displayName: security
    description: Security information associated to the endpoint
    range: ParametrizedSecurityScheme
  settings:
    displayName: settings
    description: Security scheme settings
    range: Settings
  signature:
    displayName: signature
    range: string
  tokenCredentialsUri:
    displayName: token credentials URI
    range: string
  type:
    displayName: type
    description: Type of security scheme
    range: string
